environments:
  - name: dev
    configs:
      endpoints:
        production:
          url: https://dev.x.com/iam/scim
      deploymentEnvironments:
        - displayOnDevportal: true
          deploymentEnvironment: Default
          deploymentVhost: localhost
      certs:
        - hostName: dev.x.com
          alias: backendDev
          path: backendDev.crt
      policies:
        - Gold

  - name: qa
    configs:
      endpoints:
        production:
          url: https://qa.x.com/iam/scim
      deploymentEnvironments:
        - displayOnDevportal: true
          deploymentEnvironment: Default
          deploymentVhost: localhost
      certs:
        - hostName: qa.x.com
          alias: backendQA
          path: backendQA.crt
      policies:
        - Unlimited
        - Gold